name: Test GitHub Action
env: 
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

# This triggers the workflow on push or pull request events to any branch
on:
  push:
    branches:
      - '*'  # Triggers on push to any branch
  pull_request:
    branches:
      - '*'  # Triggers on pull request for any branch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Simple "Hello, World!" output
      - name: Print Hello World
        run: echo "Hello, World! This is a GitHub Actions test."
             
      # Step 2: Print GitHub token permissions
      - name: Print GitHub Token Permissions
        run: |
          # Show permissions that are currently set in the workflow
          echo "Workflow permissions:"
          echo "contents: ${permissions.contents}"
          echo "pull-requests: ${permissions.pull-requests}"
          echo "issues: ${permissions.issues}"
          echo "statuses: ${permissions.statuses}"
          echo "deployments: ${permissions.deployments}"
          echo "repository: ${permissions.repository}"
