name: Check Merge Permissions

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on pull request events

jobs:
  check-permissions:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Check merge permissions using GitHub API
      - name: Check Merge Permissions
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GH_TOKEN }}

          echo "Fetching pull request details..."
          PR_INFO=$(curl -s -H "Authorization: token $TOKEN" \
                            -H "Accept: application/vnd.github.v3+json" \
                            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER")

          echo "PR Information:"
          echo "$PR_INFO"

          # Check mergeability
          MERGEABLE=$(echo "$PR_INFO" | jq --raw-output .mergeable)
          echo "Mergeable: $MERGEABLE"

          if [ "$MERGEABLE" = "true" ]; then
            echo "You have permission to merge this pull request."
          else
            echo "You do not have permission to merge this pull request."
          fi

          # Optional: Check if the user has admin rights
          USER_PERMISSIONS=$(curl -s -H "Authorization: token $TOKEN" \
                                     -H "Accept: application/vnd.github.v3+json" \
                                     "https://api.github.com/repos/$REPO/collaborators/${{ github.actor }}/permission")
          echo "User permissions:"
          echo "$USER_PERMISSIONS"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
