name: Test GitHub Action
env: 
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

# This triggers the workflow on push or pull request events to any branch
on:
  push:
    branches:
      - '*'  # Triggers on push to any branch
  pull_request:
    branches:
      - '*'  # Triggers on pull request for any branch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Simple "Hello, World!" output
      - name: Print Hello World
        run: echo "Hello, World! This is a GitHub Actions test."
        
      # Step 3: Print workflow context
      - name: Print Workflow Context
        run: |
          echo "GitHub Workflow Context:"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"

      # Step 4: Print information about the GitHub token being used
      - name: Print Token Information
        run: |
          echo "GitHub Actions Token Information:"
          echo "Token used: ${{ secrets.GH_TOKEN }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Set the token as an environment variable

      # Step 5: Test using the token
      - name: Use Token to Test API Call
        run: |
          echo "Testing GitHub API call with GH_TOKEN"
          curl -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}